### PR TITLE
Upgrade maven-surefire-plugin to version 2.21.0 (which is Java 10 com…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…patible)

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@joel-costigliola It would be great to have a release with this change, so that assertj-core can be tested on java 10.

**Comment by joel-costigliola** [comment]
My bad, I just run the versions plugin to see what needed to be updated but it did not show up.
I'll do another release today, it's pretty straightforward.

**Comment by PascalSchumacher** [comment]
Thanks. 😃 

Did you run "mvn versions:display-plugin-updates"? That displays me some additional updates.

**Comment by joel-costigliola** [comment]
I did, I was actually surprised not to see any updates, just maven complaining about the prerequisistes.

**Comment by PascalSchumacher** [comment]
I get:
```
[INFO] The following plugin updates are available:
[INFO]   maven-clean-plugin ................................... 3.0.0 -> 3.1.0
[INFO]   maven-jar-plugin ..................................... 3.0.2 -> 3.1.0
[INFO]   maven-resources-plugin ............................... 3.0.2 -> 3.1.0
[INFO]   maven-site-plugin ...................................... 3.6 -> 3.7.1
[INFO]   maven-surefire-plugin .............................. 2.20.1 -> 2.21.0
[INFO]   maven-surefire-report-plugin ....................... 2.20.1 -> 2.21.0
[INFO]   org.jacoco:jacoco-maven-plugin ....................... 0.7.9 -> 0.8.1
```

The current suggested way to enforce the maven version is to use the maven enforcer plugin instead of prerequisites. Sadly the versions plugin does not "understand" this, as there is no release with the fix for https://github.com/mojohaus/versions-maven-plugin/issues/48 yet.

**Comment by joel-costigliola** [comment]
I might have run another command then ... anyway no big deal.

**Comment by joel-costigliola** [comment]
I did run `mvn versions:display-plugin-updates` but with different results ... weird!
```
~/prog/assertj/assertj-maven-parent-pom ∙ mvn versions:display-plugin-updates
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[WARNING] The project org.assertj:assertj-parent-pom:pom:2.1.11-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] 
[INFO] -------------------< org.assertj:assertj-parent-pom >-------------------
[INFO] Building AssertJ - Fluent assertions for java unit testing 2.1.11-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.5:display-plugin-updates (default-cli) @ assertj-parent-pom ---
[INFO] 
[INFO] All plugins with a version specified are using the latest versions.
[INFO] 
[INFO] All plugins have a version specified.
[INFO] 
[INFO] Project defines minimum Maven version as: 3.5.0
[INFO] Plugins require minimum Maven version of: 3.0.4
[INFO] 
[INFO] No plugins require a newer version of Maven than specified by the pom.
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.041 s
[INFO] Finished at: 2018-05-17T22:12:30+12:00
[INFO] ------------------------------------------------------------------------
```
@PascalSchumacher any idea what I am missing here ?

**Comment by joel-costigliola** [comment]
I'm running into this: https://github.com/mojohaus/versions-maven-plugin/issues/48

**Comment by PascalSchumacher** [comment]
Update was done in: https://github.com/joel-costigliola/assertj-maven-parent-pom/commit/ed20a86b23f617fa31cb37849ec91939f63fa05a therefore I'm closing this.

**Pull request closed without merging**
