### PR TITLE
update findbugs-maven-plugin version to 3.0.3 and configure it to spe…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…nt maximum effort

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@joel-costigliola What about merging this?

**Comment by joel-costigliola** [comment]
I wanted to test it before integrating, I'm not always fond of some findbugs violations, some parts of AssertJ don;t follow the strict findbugs rules for good reason. I don't want to fail the build in that case.

**Comment by PascalSchumacher** [comment]
Thanks for the info. 

As there are already some violations (at least in AssertJ core) I believe that some more won't make a difference. Is the build configured to only allow a limited number of findbug violations?

**Comment by PascalSchumacher** [comment]
As far as I can tell the build won't fail even if there are more violations.

**Pull request merged**
