### PR TITLE
[mvn] Update maven wrapper to 0.4.0 (removes jar from git)

### PR DESCRIPTION
**Pull request by hazendaz**
Version 0.4.0 introduces solution to remove the maven wrapper jar from source.

### CODE REVIEW

**Comment by hazendaz** [comment]
rebased with current master.

**Comment by joel-costigliola** [comment]
@hazendaz Can you clarify what we get with these changes except removing one jar from git? 
The changes add quite a bit of code to maintain, I want to make sure the benefits outweigh the costs.

**Comment by hazendaz** [comment]
@joel-costigliola Sure, the maven wrapper is 100% untouched from [maven-wrapper](https://github.com/takari/maven-wrapper).  When the builds are run on travis, the maven wrapper is used instead of the default that travis supports.  So there is really no support here other than upgraded every so often when takari puts out an update.  They also have a maven run you can execute that will actually just update the items for you so there is no copy paste involved.  You can find that [here](https://github.com/takari/takari-maven-plugin)

**Comment by joel-costigliola** [comment]
Thanks @hazendaz.

**Pull request merged**
