### PR TITLE
Update Java version to 8.

### PR DESCRIPTION
**Pull request by croesch**
Is there any reason not to update Java in the parent pom? Saw that assertj-core includes the version now in its pom..

### CODE REVIEW

**Comment by joel-costigliola** [comment]
I only have assertj-core 3.x  on java 8, all the other ones are using java 7. That's why I overrode it directly in assertj-core 3.x pom.
I don't mind having a java 8 parent pom (useful when multiple projects are on java 8), we can either create a java-8  branch of this project and make the necessary update or just have sub parent pom overriding the java version. The former option is cleaner IMO but requires to keep the pom in sync for plugins version updates, the latter does not have this problem but does not feel super clean to me.

Anyway we can do choose either options, keeping the pom in sync is not too difficult.

**Comment by croesch** [comment]
How about doing the first approach (own branch) but on the master?

So master will get an increased minor or major version and we create a Java 7 compatible branch. And in the modules that don't use Java 8 we can use the 1.3.x branch until they jump on Java 8.

I would prefer Java 8 on the master as it is clear that this is the future and Java 7 is passing..

**Comment by joel-costigliola** [comment]
I will release a 2.0 parent pom using java 8 soonish.

**Comment by joel-costigliola** [comment]
Done.

**Comment by croesch** [comment]
Thank you very much!!!

**Pull request closed without merging**
