### PR TITLE
Some maven goodness and cleanup

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks !
I was planning to do that before releasing 2.0 in a few weeks.

**Comment by hazendaz** [comment]
Any status on this PR?

**Comment by joel-costigliola** [comment]
Status = I have forgotten !
Will have a look at it soon bit for real this time.

Thanks for reminding me :)

**Comment by hazendaz** [comment]
Sure…I was just going back through old PRs and thought I’d reach out.

 

Thanks,

 

Jeremy

**Comment by joel-costigliola** [comment]
Thanks for the help.

**Comment by hazendaz** [comment]
You’re welcome!

**Pull request merged**
